import org.apache.hadoop.security.protocolPB.RefreshAuthorizationPolicyProtocolClientSideTranslatorPB;
public class FunctionUse11835 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolClientSideTranslatorPB refreshauthorizationpolicyprotocolclientsidetranslatorpb = new RefreshAuthorizationPolicyProtocolClientSideTranslatorPB();
}
}